#!/usr/bin/env bash
# This is a bash script manages "manage_my_process"

#!/usr/bin/env bash
# Manages 'manage_my_process'

if [ $# -gt 0 ]
then
    if [ "$1" == "start" ]
    then
# Start the process in the background and store its PID
	./manage_my_process &
	touch /var/run/my_process.pid

	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
    elif [ "$1" == "stop" ]
    then
# Stop the process by sending a signal to its PID
	echo "manage_my_process stopped"
	kill "$(cat /var/run/my_process.pid)"
	rm -f /var/run/my_process.pid
    elif [ "$1" == "restart" ]
    then
# Restart the process
	kill "$(cat /var/run/my_process.pid)"
	rm -f /var/run/my_process.pid
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
    else
	echo "Usage: manage_my_process {start|stop|restart}"
    fi
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
