#!/usr/bin/env bash
# This bash script displays "To infinity and beyond" indefinitely
# In between each iteration of the loop adds a "sleep 2"

while true
do
	echo "To infinity and beyond"
	sleep 2
done
