#!/usr/bin/env bash
# Use ssh with the -i flag to specify the private key file
# Use the -o flag to disable password authentication
# Use the user@host format to specify the user and host

ssh ubuntu -i ~/.ssh/school
